language: python
python: 
  - "3.6"
 
# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
script:
  - python ./test/scoreboardTest.py
  - python ./test/mainGameTest.py