language: python
python: 
  - "3.6"
 
# command to install dependencies
install:
  - pip install -r requirements.txt

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
script:
  - python ./test/scoreboardTest.py
  - python ./test/mainGameTest.py

CODECOV_TOKEN: "51af92ba-ad39-4c25-a64f-44e4e1a947a6"

after_success:
 - bash <(curl -s https://codecov.io/bash)