language: python
python: 
  - "3.6"
 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
script:
  - coverage run ./test/scoreboardTest.py
  - codecov
  - coverage run ./test/mainGameTest.py
  - codecov
  - coverage run ./test/chessboardTest.py
  - codecov
  - coverage run ./test/gameLogicTest.py

  